-- 案件ステータスに「再訪問」(revisit) を追加する。
-- 画面の語彙: 確定 / 訪問完了 / 回収待ち / 再訪問 / 完了 / キャンセル
-- ※ visiting(訪問中) は選択肢から外したが、既存行の表示のため語彙としては残す。
--
-- ★本番(2026-08-18時点)では実行不要★
--   本番の cases.status は enum ではなく text 列で作られている（0001 の定義とズレている。
--   同様に documents.type も text）。text なので 'revisit' はそのまま保存できる。
--   実際に本番で書き込み確認済み。
--
-- 下のDDLは、0001 を素直に適用して case_status enum が存在する環境（新規に作り直した場合など）
-- のためのもの。enum が無い環境で実行すると 42704 (type does not exist) になるので、
-- その場合は実行しなくてよい。
alter type case_status add value if not exists 'revisit';
